// import { borderColor } from "polished";
// import { useTheme } from "../components/GlueStackThemeProvider";

// Hook to get global design tokens
export const useTokens = () => {
	// const { colors } = useTheme();

	return {
		// Layout
		flex1: { flex: 1 },
		itemsCenter: { alignItems: "center" as const },
		itemsStart: { alignItems: "flex-start" as const },
		itemsEnd: { alignItems: "flex-end" as const },
		justifyCenter: { justifyContent: "center" as const },
		justifyBetween: { justifyContent: "space-between" as const },
		justifyAround: { justifyContent: "space-around" as const },
		justifyEvenly: { justifyContent: "space-evenly" as const },
		flexRow: { flexDirection: "row" as const },
		flexCol: { flexDirection: "column" as const },

		// Spacing
		p1: { padding: 4 },
		p2: { padding: 8 },
		p3: { padding: 12 },
		p4: { padding: 16 },
		p5: { padding: 20 },
		p6: { padding: 24 },
		p8: { padding: 32 },
		px1: { paddingHorizontal: 4 },
		px2: { paddingHorizontal: 8 },
		px3: { paddingHorizontal: 12 },
		px4: { paddingHorizontal: 16 },
		px5: { paddingHorizontal: 20 },
		px6: { paddingHorizontal: 24 },
		py1: { paddingVertical: 4 },
		py2: { paddingVertical: 8 },
		py3: { paddingVertical: 12 },
		py4: { paddingVertical: 16 },
		py5: { paddingVertical: 20 },
		py6: { paddingVertical: 24 },
		pt1: { paddingTop: 4 },
		pt2: { paddingTop: 8 },
		pt3: { paddingTop: 12 },
		pt4: { paddingTop: 16 },
		pt5: { paddingTop: 20 },
		pt6: { paddingTop: 24 },
		pb1: { paddingBottom: 4 },
		pb2: { paddingBottom: 8 },
		pb3: { paddingBottom: 12 },
		pb4: { paddingBottom: 16 },
		pb5: { paddingBottom: 20 },
		pb6: { paddingBottom: 24 },
		pb7: { paddingBottom: 28 },
		pb8: { paddingBottom: 32 },
		pb9: { paddingBottom: 36 },
		pb10: { paddingBottom: 40 },
		pb11: { paddingBottom: 44 },
		pb12: { paddingBottom: 48 },
		pb13: { paddingBottom: 52 },
		pb14: { paddingBottom: 56 },
		pb15: { paddingBottom: 60 },
		pb16: { paddingBottom: 64 },
		pb17: { paddingBottom: 68 },
		pb18: { paddingBottom: 72 },
		pl1: { paddingLeft: 4 },
		pl2: { paddingLeft: 8 },
		pl3: { paddingLeft: 12 },
		pl4: { paddingLeft: 16 },
		pr1: { paddingRight: 4 },
		pr2: { paddingRight: 8 },
		pr3: { paddingRight: 12 },
		pr4: { paddingRight: 16 },

		m1: { margin: 4 },
		m2: { margin: 8 },
		m3: { margin: 12 },
		m4: { margin: 16 },
		m5: { margin: 20 },
		m6: { margin: 24 },
		m8: { margin: 32 },
		mauto: { margin: "auto" as "auto" },
		mx1: { marginHorizontal: 4 },
		mx2: { marginHorizontal: 8 },
		mx3: { marginHorizontal: 12 },
		mx4: { marginHorizontal: 16 },
		mx5: { marginHorizontal: 20 },
		mx6: { marginHorizontal: 24 },
		mxauto: { marginHorizontal: "auto" as "auto" },
		my1: { marginVertical: 4 },
		my2: { marginVertical: 8 },
		my3: { marginVertical: 12 },
		my4: { marginVertical: 16 },
		my5: { marginVertical: 20 },
		my6: { marginVertical: 24 },
		myauto: { marginVertical: "auto" as "auto" },
		mt1: { marginTop: 4 },
		mt2: { marginTop: 8 },
		mt3: { marginTop: 12 },
		mt4: { marginTop: 16 },
		mt5: { marginTop: 20 },
		mt6: { marginTop: 24 },
		mtauto: { marginTop: "auto" as "auto" },
		mb1: { marginBottom: 4 },
		mb2: { marginBottom: 8 },
		mb3: { marginBottom: 12 },
		mb4: { marginBottom: 16 },
		mb5: { marginBottom: 20 },
		mb6: { marginBottom: 24 },
		mb7: { marginBottom: 28 },
		mb8: { marginBottom: 32 },
		mbauto: { marginBottom: "auto" as "auto" },
		ml1: { marginLeft: 4 },
		ml2: { marginLeft: 8 },
		ml3: { marginLeft: 12 },
		ml4: { marginLeft: 16 },
		mlauto: { marginLeft: "auto" as "auto" },
		mr1: { marginRight: 4 },
		mr2: { marginRight: 8 },
		mr3: { marginRight: 12 },
		mr4: { marginRight: 16 },
		mrauto: { marginRight: "auto" as "auto" },

		gap1: { gap: 4 },
		gap2: { gap: 8 },
		gap3: { gap: 12 },
		gap4: { gap: 16 },
		gap5: { gap: 20 },
		gap6: { gap: 24 },
		gap7: { gap: 32 },
		gap8: { gap: 36 },
		gap9: { gap: 40 },
		gap10: { gap: 44 },

		// Colors (Dynamic based on current theme)
		// bgBackground: { backgroundColor: colors.background },
		// bgSurface: { backgroundColor: colors.surface },
		// bgPrimary: { backgroundColor: colors.primary },
		// bgSecondary: { backgroundColor: colors.secondary },
		// bgSuccess: { backgroundColor: colors.success },
		// bgWarning: { backgroundColor: colors.warning },
		// bgError: { backgroundColor: colors.error },
		// bgInfo: { backgroundColor: colors.info },
		// bgTransparent: { backgroundColor: "transparent" },
		// bgWhite: { backgroundColor: "white" },
		// bgBlack: { backgroundColor: "black" },
		// bgLight: { backgroundColor: colors.light },
		// 	bgProgressBarLight: { backgroundColor: "#ACA8FF"},

		// textPrimary: { color: colors.text },
		// textSecondary: { color: colors.textSecondary },
		// textMuted: { color: colors.textMuted },
		// textWhite: { color: "white" },
		// textBlack: { color: "black" },
		// colorPrimary: { color: colors.primary },
		// colorSecondary: { color: colors.secondary },
		// colorSuccess: { color: colors.success },
		// colorWarning: { color: colors.warning },
		// colorError: { color: colors.error },
		// colorInfo: { color: colors.info },

		// colorNeutral: {
		// 	100: {color: colors.neutral.100}
		// }
		// colorLight: { colors: colors.light },

		// Borders
		// borderPrimary: { borderColor: colors.border },
		// borderError: { borderColor: colors.error },
		// borderSuccess: { borderColor: colors.success },
		// borderLight: { borderColor: colors.light },
		border: { borderWidth: 1 },
		border2: { borderWidth: 2 },
		borderT: { borderTopWidth: 1 },
		borderB: { borderBottomWidth: 1 },
		borderL: { borderLeftWidth: 1 },
		borderR: { borderRightWidth: 1 },

		// Typography
		textXxsm: { fontSize: 8 },
		textXsm: { fontSize: 10 },
		textXs: { fontSize: 12 },
		textSm: { fontSize: 14 },
		textBase: { fontSize: 16 },
		textLg: { fontSize: 18 },
		textXl: { fontSize: 20 },
		text2xl: { fontSize: 24 },
		text3xl: { fontSize: 30 },
		text4xl: { fontSize: 36 },

		fontThin: { fontWeight: "100" as const },
		fontLight: { fontWeight: "300" as const },
		fontNormal: { fontWeight: "400" as const },
		fontMedium: { fontWeight: "500" as const },
		fontSemibold: { fontWeight: "600" as const },
		fontBold: { fontWeight: "700" as const },
		fontExtrabold: { fontWeight: "800" as const },
		fontBlack: { fontWeight: "900" as const },

		textLeft: { textAlign: "left" as const },
		textCenter: { textAlign: "center" as const },
		textRight: { textAlign: "right" as const },

		// Font Families
		fontClashGrotesk: { fontFamily: "ClashGrotesk-Regular" },
		fontClashGroteskLight: { fontFamily: "ClashGrotesk-Regular" },
		fontClashGroteskMedium: { fontFamily: "ClashGrotesk-Medium" },
		fontClashGroteskSemibold: { fontFamily: "ClashGrotesk-Semibold" },
		fontClashGroteskBold: { fontFamily: "ClashGrotesk-Bold" },

		// Borders & Shapes
		rounded: { borderRadius: 8 },
		roundedSm: { borderRadius: 4 },
		roundedMd: { borderRadius: 6 },
		roundedLg: { borderRadius: 12 },
		roundedXl: { borderRadius: 16 },
		rounded2xl: { borderRadius: 20 },
		rounded3xl: { borderRadius: 24 },
		roundedFull: { borderRadius: 9999 },

		roundedT: { borderTopLeftRadius: 8, borderTopRightRadius: 8 },
		roundedTlg: { borderTopLeftRadius: 12, borderTopRightRadius: 12 },
		roundedTXlg: { borderTopLeftRadius: 16, borderTopRightRadius: 16 },
		roundedB: { borderBottomLeftRadius: 8, borderBottomRightRadius: 8 },
		roundedL: { borderTopLeftRadius: 8, borderBottomLeftRadius: 8 },
		roundedR: { borderTopRightRadius: 8, borderBottomRightRadius: 8 },

		// Sizing
		w4: { width: 16 },
		w5: { width: 20 },
		w6: { width: 24 },
		w8: { width: 32 },
		w10: { width: 40 },
		w12: { width: 48 },
		w16: { width: 64 },
		w20: { width: 80 },
		w24: { width: 96 },
		w32: { width: 128 },
		wFull: { width: "100%" as "100%" },

		h1: { height: 2 },
		h2: { height: 4 },
		h3: { height: 8 },
		h4: { height: 16 },
		h5: { height: 20 },
		h6: { height: 24 },
		h8: { height: 32 },
		h10: { height: 40 },
		h12: { height: 48 },
		h16: { height: 64 },
		h20: { height: 80 },
		h24: { height: 96 },
		h32: { height: 128 },
		hFull: { height: "100%" as "100%" },

		// Position
		absolute: { position: "absolute" as const },
		relative: { position: "relative" as const },

		top0: { top: 0 },
		top1: { top: 4 },
		top2: { top: 8 },
		top4: { top: 16 },

		bottom0: { bottom: 0 },
		bottom1: { bottom: 4 },
		bottom2: { bottom: 8 },
		bottom4: { bottom: 16 },
		bottom5: { bottom: 32},
		bottom6: { bottom: 64},
		bottom7: { bottom: 85},

		left0: { left: 0 },
		left1: { left: 4 },
		left2: { left: 8 },
		left4: { left: 16 },

		right0: { right: 0 },
		right1: { right: 4 },
		right2: { right: 8 },
		right4: { right: 16 },

		// Shadow
		shadow: {
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 2 },
			shadowOpacity: 0.1,
			shadowRadius: 4,
			elevation: 3,
		},
		shadowSm: {
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 1 },
			shadowOpacity: 0.05,
			shadowRadius: 2,
			elevation: 1,
		},
		shadowMd: {
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 4 },
			shadowOpacity: 0.15,
			shadowRadius: 6,
			elevation: 4,
		},
		shadowLg: {
			shadowColor: "#000",
			shadowOffset: { width: 0, height: 6 },
			shadowOpacity: 0.2,
			shadowRadius: 8,
			elevation: 6,
		},
		shadowNone: {
			shadowColor: "transparent",
			shadowOffset: { width: 0, height: 0 },
			shadowOpacity: 0,
			shadowRadius: 0,
			elevation: 0,
		},

		// Opacity
		opacity0: { opacity: 0 },
		opacity25: { opacity: 0.25 },
		opacity50: { opacity: 0.5 },
		opacity75: { opacity: 0.75 },
		opacity100: { opacity: 1 },

		// Display
		hidden: { display: "none" as const },
		flex: { display: "flex" as const },
	};
};
